{{/* code: language=goyaml */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-jwks-server.fullname" . }}
  labels:
    {{- include "go-jwks-server.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "go-jwks-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "go-jwks-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "go-jwks-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-svc
              containerPort: 8080
              protocol: TCP
          {{/* livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http */}}
          env:
            {{- range .Values.envVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- include "zeus-svc-helper.go-jwks-server-config-env-vars" . | indent 12 }}
          {{- if .Values.keysSecretName }}
          volumeMounts:
            - name: jwks-public-keys
              mountPath: {{ .Values.key_dir }}
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{ if .Values.keysSecretName }}
      volumes:
      - name: jwks-public-keys
        secret:
          secretName: {{ .Values.keysSecretName }}
          optional: {{ .Values.keysSecretOptional | default false }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
